AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 instances for Fuel Flow application'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

  InstanceType:
    Type: String
    Default: t3.micro
    Description: EC2 instance type

  KeyName:
    Type: String
    Default: ''
    Description: EC2 key pair name (optional)

  InstanceCount:
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 10
    Description: Number of EC2 instances to create

  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    Description: Latest Amazon Linux 2 AMI ID

Conditions:
  HasKeyName: !Not [!Equals [!Ref KeyName, '']]

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub 'fuel-flow-ec2-sg-${Environment}'
      GroupDescription: Security group for Fuel Flow EC2 instances
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: SSH access
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: HTTP access
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: HTTPS access
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic
      Tags:
        - Key: Name
          Value: !Sub 'fuel-flow-ec2-sg-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'fuel-flow-ec2-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::fuel-flow-${Environment}-*'
                  - !Sub 'arn:aws:s3:::fuel-flow-${Environment}-*/*'
      Tags:
        - Key: Name
          Value: !Sub 'fuel-flow-ec2-role-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub 'fuel-flow-ec2-profile-${Environment}'
      Roles:
        - !Ref EC2InstanceRole

  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      KeyName: !If [HasKeyName, !Ref KeyName, !Ref 'AWS::NoValue']
      IamInstanceProfile: !Ref EC2InstanceProfile
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Fuel Flow - ${Environment} Environment - Instance 1</h1>" > /var/www/html/index.html
      Tags:
        - Key: Name
          Value: !Sub 'fuel-flow-app-${Environment}-1'
        - Key: Environment
          Value: !Ref Environment

Outputs:
  InstanceId1:
    Description: Instance ID of the first EC2 instance
    Value: !Ref EC2Instance1
    Export:
      Name: !Sub '${AWS::StackName}-InstanceId1'

  PublicIp1:
    Description: Public IP of the first EC2 instance
    Value: !GetAtt EC2Instance1.PublicIp
    Export:
      Name: !Sub '${AWS::StackName}-PublicIp1'

  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref EC2SecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroupId'

  InstanceRoleArn:
    Description: IAM Role ARN for EC2 instances
    Value: !GetAtt EC2InstanceRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-InstanceRoleArn'
