AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM roles and policies for Fuel Flow application'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

Resources:
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'fuel-flow-ec2-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::fuel-flow-${Environment}-*'
                  - !Sub 'arn:aws:s3:::fuel-flow-${Environment}-*/*'
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: 'arn:aws:logs:*:*:*'
      Tags:
        - Key: Name
          Value: !Sub 'fuel-flow-ec2-role-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub 'fuel-flow-ec2-profile-${Environment}'
      Roles:
        - !Ref EC2Role

  RDSMonitoringRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'fuel-flow-rds-monitoring-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: monitoring.rds.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole
      Tags:
        - Key: Name
          Value: !Sub 'fuel-flow-rds-monitoring-role-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'fuel-flow-lambda-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::fuel-flow-${Environment}-*'
                  - !Sub 'arn:aws:s3:::fuel-flow-${Environment}-*/*'
      Tags:
        - Key: Name
          Value: !Sub 'fuel-flow-lambda-role-${Environment}'
        - Key: Environment
          Value: !Ref Environment

Outputs:
  EC2RoleArn:
    Description: ARN of the EC2 IAM role
    Value: !GetAtt EC2Role.Arn
    Export:
      Name: !Sub '${AWS::StackName}-EC2RoleArn'

  EC2InstanceProfileName:
    Description: Name of the EC2 instance profile
    Value: !Ref EC2InstanceProfile
    Export:
      Name: !Sub '${AWS::StackName}-EC2InstanceProfileName'

  RDSMonitoringRoleArn:
    Description: ARN of the RDS monitoring role
    Value: !GetAtt RDSMonitoringRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RDSMonitoringRoleArn'

  LambdaExecutionRoleArn:
    Description: ARN of the Lambda execution role
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaExecutionRoleArn'
