AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 buckets for Fuel Flow application'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

  BucketPrefix:
    Type: String
    Default: fuel-flow
    Description: Prefix for S3 bucket names

Resources:
  AppDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketPrefix}-${Environment}-app-data'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${BucketPrefix}-${Environment}-app-data'
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: Application Data

  LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketPrefix}-${Environment}-logs'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${BucketPrefix}-${Environment}-logs'
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: Application Logs

  BackupsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketPrefix}-${Environment}-backups'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${BucketPrefix}-${Environment}-backups'
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: Backups

Outputs:
  AppDataBucketName:
    Description: Name of the application data bucket
    Value: !Ref AppDataBucket
    Export:
      Name: !Sub '${AWS::StackName}-AppDataBucket'

  LogsBucketName:
    Description: Name of the logs bucket
    Value: !Ref LogsBucket
    Export:
      Name: !Sub '${AWS::StackName}-LogsBucket'

  BackupsBucketName:
    Description: Name of the backups bucket
    Value: !Ref BackupsBucket
    Export:
      Name: !Sub '${AWS::StackName}-BackupsBucket'
